# Do students access their feedback? {#feedback}

Authors: Craig Alexander and Emily Nordmann 

## Introduction

Providing feedback on student assignments is a time-consuming yet important process for teaching staff. The provision and use of effective feedback has an extremely strong relationship with performance (@hattie2008) whilst metrics such as the National Student Survey in the UK consistently record that students are less satisfied with  assessment and feedback than other aspects of their university experience. 

Yet despite this, getting students to engage with feedback provided to them can be difficult. @Mensink2020StudentAO found that when students were able to access their mark without also accessing the associated feedback, 42% of feedback files remained unopen. Similarly, kuepper2021effects found that releasing feedback prior to grades increased feedback engagement and had a relationship with increased performance in the subsesquent assessment.  Conversely, @Zimbardi2017AreTU found high engagement with feedback with 92% of first year and 85% of second year students accessing their feedback. They also found that the length of time students spent engaging with their feedback predicted improvement in subsequent assessment tasks. 

This tutorial will explain how to retrieve data on when and whether a student has accessed their feedback in Turnitin Studio via Moodle and investigate whether viewing feedback can predict their grade in subsequent assessments and whether they access future feedback.

## Data sources

To avoid any ethical issues, the data used in this chapter is a synthetic copy of real data available to the authors. The data is based on two large first-year psychology courses. In the first semester course, Psych 1A, students completed an essay (25%), exam (50%), and a portfolio of small-stakes continuous assessment tasks (25%). In the second semester course, Psych 1B, students completed a registered report (20%), exam (50%), and a portfolio of small-stakes continuous assessment tasks (30%). Students can take Psych 1A as an elective and therefore there are fewer students in the second semester than the first semester course. Grading is conducted for all assessments on a 22-point scale.

There are X datasets:

* Dataset 1 contains the grades for all students, for all individual assessments, as well as their overall course grade for Psych 1A
* Dataset 2 contains the grades for all students, for all individual assessments, as well as their overall course grade for Psych 1B
* Dataset 3 contains the Turnitin viewing logs scraped from Moodle for Psych 1A.
* Dataset 4 contains the Turnitin viewing logs scraped from Moodle for Psych 1B.


