<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 7 Combining Echo360 data with other sources of data with tidyverse | scholaRship</title>
<meta name="author" content="Emily Nordmann, Craig Alexander, James Bartlett, Eilidh Jack, Gaby Mahrholz, Jill MacKay, Mitchum Bock">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="Chapter 7 Combining Echo360 data with other sources of data with tidyverse | scholaRship">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/scholaRship/Echo_combine.html">
<meta property="og:image" content="https://psyteachr.github.io/scholaRship/images/logos/logo.png">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 7 Combining Echo360 data with other sources of data with tidyverse | scholaRship">
<meta name="twitter:image" content="https://psyteachr.github.io/scholaRship/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.0/transition.js"></script><script src="libs/bs3compat-0.5.0/tabs.js"></script><script src="libs/bs3compat-0.5.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script><script src="libs/plotly-binding-4.10.2/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
<meta name="description" content="7.1 Introduction So far, we have focused on analysing Echo360 data in isolation. However, you might be interested in combining data from multiple sources to explore if there are relationships...">
<meta property="og:description" content="7.1 Introduction So far, we have focused on analysing Echo360 data in isolation. However, you might be interested in combining data from multiple sources to explore if there are relationships...">
<meta name="twitter:description" content="7.1 Introduction So far, we have focused on analysing Echo360 data in isolation. However, you might be interested in combining data from multiple sources to explore if there are relationships...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">scholaRship</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="creating-synthetic-datasets.html"><span class="header-section-number">2</span> Creating synthetic datasets</a></li>
<li><a class="" href="moodle-assignment-submission-reports.html"><span class="header-section-number">3</span> Moodle Assignment submission reports</a></li>
<li><a class="" href="workshop.html"><span class="header-section-number">4</span> ALT Conference Prep</a></li>
<li><a class="" href="Echo_tidy.html"><span class="header-section-number">5</span> Getting started with Echo360 data with tidyverse</a></li>
<li><a class="" href="Echo_course.html"><span class="header-section-number">6</span> Exploring Echo360 video/course level data with tidyverse</a></li>
<li><a class="active" href="Echo_combine.html"><span class="header-section-number">7</span> Combining Echo360 data with other sources of data with tidyverse</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="symbols.html"><span class="header-section-number">B</span> Symbols</a></li>
<li><a class="" href="conventions.html"><span class="header-section-number">C</span> Conventions</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references-1.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/scholaRship">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="Echo_combine" class="section level1" number="7">
<h1>
<span class="header-section-number">7</span> Combining Echo360 data with other sources of data with <code>tidyverse</code><a class="anchor" aria-label="anchor" href="#Echo_combine"><i class="fas fa-link"></i></a>
</h1>
<div id="introduction-2" class="section level2" number="7.1">
<h2>
<span class="header-section-number">7.1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction-2"><i class="fas fa-link"></i></a>
</h2>
<p>So far, we have focused on analysing Echo360 data in isolation. However, you might be interested in combining data from multiple sources to explore if there are relationships between lecture capture and engagement/attainment data.</p>
<p>In this tutorial, we will demonstrate how you can combine data from multiple sources and the kind of identifiers you will need to match people across data sets. In addition to Echo360 data we have used so far, we also have two types of data from the virtual learning environment (VLE) Moodle, based on an introductory research methods course (RM1). We have mock checklist data for how many tasks people complete each week and mock attainment data for scores on a multiple choice quiz (MCQ). We applied the same synthetic data process and created anonymous names and emails to provide consistent information across files to join.</p>
<p>To follow the tutorial, please download the Echo360 and Moodle data from <a href="data/Combine_data.zip">this .zip file.</a>.</p>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span> <span class="co"># Package of packages for plotting and wrangling </span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://plotly-r.com">plotly</a></span><span class="op">)</span> <span class="co"># Creates interactive plots </span></span></code></pre></div>
<pre><code>## 
## Attaching package: 'plotly'</code></pre>
<pre><code>## The following object is masked from 'package:ggplot2':
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from 'package:stats':
## 
##     filter</code></pre>
<pre><code>## The following object is masked from 'package:graphics':
## 
##     layout</code></pre>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rpkgs.datanovia.com/ggpubr/">ggpubr</a></span><span class="op">)</span> <span class="co"># Builds on ggplot2 to build specific publication ready plots </span></span></code></pre></div>
</div>
<div id="reading-in-the-data" class="section level2" number="7.2">
<h2>
<span class="header-section-number">7.2</span> Reading in the data<a class="anchor" aria-label="anchor" href="#reading-in-the-data"><i class="fas fa-link"></i></a>
</h2>
<p>The first step is to read in the data we need for the tutorial. For the first example, we will read in data from one lecture. For later examples, we will combine data from multiple lectures. We only have three lectures of Echo360 data for this course, but to reduce repetition and scale better if you are working with more files, we will still read in data by listing files instead of assigning each file individually to an object. We are using relatives paths for the tutorial and assume you have a folder called <code>data</code> in your working directory and two subfolders called <code>RM1_duplicate</code> and <code>Moodle_duplicate</code>. If you saved the data in another way, you will need to edit the paths.</p>
<div class="sourceCode" id="cb117"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># One lecture for an example </span></span>
<span><span class="va">lecture_01</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/RM1_duplicate/Lecture01.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Reading the Echo360 data from three lectures into one data object</span></span>
<span><span class="co"># Obtain list of files from directory</span></span>
<span><span class="va">files</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span><span class="op">(</span>path<span class="op">=</span><span class="st">"data/RM1_duplicate/"</span>, </span>
<span>                    pattern<span class="op">=</span><span class="st">".csv"</span>, </span>
<span>                    full.names <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># Read in all the files to one object and label each file name</span></span>
<span><span class="va">Echo360_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">files</span>,</span>
<span>                         id<span class="op">=</span><span class="st">"file_name"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Preview the columns and data</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">Echo360_data</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 145
## Columns: 16
## $ file_name         &lt;chr&gt; "data/RM1_duplicate/Lecture01.csv", "data/RM1_duplic…
## $ media_id          &lt;chr&gt; "28dcfb20-a198-438b-8dbe-1b5725514231", "28dcfb20-a1…
## $ media_name        &lt;chr&gt; "RM1 Lecture 1", "RM1 Lecture 1", "RM1 Lecture 1", "…
## $ create_date       &lt;chr&gt; "09/23/2022", "09/23/2022", "09/23/2022", "09/23/202…
## $ duration          &lt;time&gt; 01:00:00, 01:00:00, 01:00:00, 01:00:00, 01:00:00, 0…
## $ owner_name        &lt;chr&gt; "James Bartlett", "James Bartlett", "James Bartlett"…
## $ course            &lt;chr&gt; "Research Methods 1 (PGT Conv)", "Research Methods 1…
## $ user_name         &lt;chr&gt; "Yaw, Collin", "Viaan, Jordan", NA, NA, "Sunny, Hali…
## $ email_address     &lt;chr&gt; "214488@university.ac.uk", "211717@university.ac.uk"…
## $ total_views       &lt;dbl&gt; 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 1, 2, 1, 3, 3, 1, 1, 5…
## $ total_view_time   &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:04:30, 00:01:00, 0…
## $ average_view_time &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:01:30, 00:01:00, 0…
## $ on_demand_views   &lt;dbl&gt; 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 1, 2, 1, 3, 3, 1, 1, 5…
## $ live_view_count   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ downloads         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ last_viewed       &lt;chr&gt; "11/04/2022", "09/30/2022", "02/10/2023", "10/21/202…</code></pre>
<p>We only have individual files for the checklist and MCQ data, so we can assign those to individual objects.</p>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Reading student data from other Moodle activities into two data objects</span></span>
<span><span class="va">Checklist</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/Moodle_duplicate/Checklist.csv"</span><span class="op">)</span>  <span class="co">#A log of checklist elements clicked</span></span>
<span></span>
<span><span class="va">MCQ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/Moodle_duplicate/MCQ.csv"</span><span class="op">)</span>  <span class="co">#Results from Multiple Choice Quiz</span></span></code></pre></div>
</div>
<div id="joining-data-using-dplyr" class="section level2" number="7.3">
<h2>
<span class="header-section-number">7.3</span> Joining data using <code>dplyr</code><a class="anchor" aria-label="anchor" href="#joining-data-using-dplyr"><i class="fas fa-link"></i></a>
</h2>
<p>The <code class="package">dplyr</code> package in <code>tidyverse</code> has several functions that merge or "join" data. There are several versions of these functions depending on how you want to join the files. For a detailed overview, please refer to the <a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">dplyr reference page online</a>.</p>
<p>There are two main types of joins which add and match columns from two data frames. There is <code><span><span class="fu">inner_join</span><span class="op">(</span><span class="op">)</span></span></code> which only retains observations from data frame 1 that also has a matching case in data frame 2. There are then different types of outer joins which retain observations that appear in at least one data frame, such as <code><span><span class="fu">left_join</span><span class="op">(</span><span class="op">)</span></span></code> which retains all observations in data frame 1.</p>
<p>To illustrate these functions, we will consider data from Echo360 together with data from a checklist which records the percentage of tasks that student have marked as complete and also with data containing the results of a multiple choice quiz. In both the checklist and MCQ data objects, each student only appears once.</p>
<div id="merging-data-where-each-student-only-appears-once-in-each-data-object" class="section level3" number="7.3.1">
<h3>
<span class="header-section-number">7.3.1</span> Merging data where each student only appears once in each data object<a class="anchor" aria-label="anchor" href="#merging-data-where-each-student-only-appears-once-in-each-data-object"><i class="fas fa-link"></i></a>
</h3>
<p>If you are interested in combining Echo360 data from just one lecture (and thus where each student will appear once) together with the MCQ data we could follow the following steps.</p>
<p>First, select the variables of interest from each data object, where <code>lecture_01</code> contains the Echo360 data from the first lecture.</p>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Manually select which columns to retain</span></span>
<span><span class="va">lecture_01_merge</span> <span class="op">&lt;-</span> <span class="va">lecture_01</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">user_name</span>,</span>
<span>         <span class="va">email_address</span>,</span>
<span>         <span class="va">total_views</span>,</span>
<span>         <span class="va">total_view_time</span>,</span>
<span>         <span class="va">average_view_time</span>,</span>
<span>         <span class="va">last_viewed</span><span class="op">)</span></span>
<span></span>
<span><span class="va">MCQ_merge</span> <span class="op">&lt;-</span> <span class="va">MCQ</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">first_name</span>,</span>
<span>         <span class="va">surname</span>,</span>
<span>         <span class="va">id_number</span>,</span>
<span>         <span class="va">email_address</span>,</span>
<span>         <span class="va">quiz_mcq_summative_assessment_real</span>,</span>
<span>         <span class="va">quiz_mcq_summative_assessment_perc</span><span class="op">)</span></span></code></pre></div>
<p>Second, specify the type of 'join' to apply. For this tutorial, we will demonstrate the different types of join to show how the resulting objects differ. Echo360 and Moodle store data differently, so we will need an identifier to use as a key to link people from both files. The participants' email is the only consistent identifier, so we will use that to link participants across files. Other identifying information like the name and student ID number are not consistent across files.</p>
<div id="left_join" class="section level4" number="7.3.1.1">
<h4>
<span class="header-section-number">7.3.1.1</span> <code>left_join()</code><a class="anchor" aria-label="anchor" href="#left_join"><i class="fas fa-link"></i></a>
</h4>
<p>The first type is <code><span><span class="fu">left_join</span><span class="op">(</span><span class="op">)</span></span></code> which retains all observations in data frame 1, meaning we keep everything in <code>lecture_01_merge</code> and add information from <code>MCQ_merge</code>. We state <code>email_address</code> as the shared variable to act as the key.</p>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lecture_01_MCQ_left</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">lecture_01_merge</span>,</span>
<span>                                <span class="va">MCQ_merge</span>, </span>
<span>                                by <span class="op">=</span> <span class="st">"email_address"</span><span class="op">)</span></span></code></pre></div>
<p>It is important you explore the resulting data frame to make sure everything is as expected.</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">lecture_01_MCQ_left</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 67
## Columns: 11
## $ user_name                          &lt;chr&gt; "Yaw, Collin", "Viaan, Jordan", NA,…
## $ email_address                      &lt;chr&gt; "214488@university.ac.uk", "211717@…
## $ total_views                        &lt;dbl&gt; 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 1, 2,…
## $ total_view_time                    &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:0…
## $ average_view_time                  &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:0…
## $ last_viewed                        &lt;chr&gt; "11/04/2022", "09/30/2022", "02/10/…
## $ first_name                         &lt;chr&gt; "Collin", "Jordan", NA, NA, "Hali",…
## $ surname                            &lt;chr&gt; "Yaw", "Viaan", NA, NA, "Sunny", "T…
## $ id_number                          &lt;int&gt; 214488, 211717, NA, NA, 278359, 272…
## $ quiz_mcq_summative_assessment_real &lt;int&gt; 17, 22, NA, NA, 19, 19, 22, NA, 20,…
## $ quiz_mcq_summative_assessment_perc &lt;dbl&gt; 77.27273, 100.00000, NA, NA, 86.363…</code></pre>
<p>We started with 67 rows for the Echo360 data and 243 rows for the MCQ data, but because we only wanted to retain all Echo360 observations, we ended up with 67 rows.</p>
<div class="info">
<p>If you do not enter a column to act as the key, <code>dplyr</code> will do its best to identify if there are two columns with the same name. It will warn you about this to make sure you double check it is using the right variables. In the first example, the variable also has the same name which makes things easier. However, you might find the same information has a different name, so you can tell <code>dplyr</code> which two columns you want to use as the joining key. See what these alternatives look like below.</p>
</div>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Warning which column it is joining by</span></span>
<span><span class="va">lecture_01_MCQ_left</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">lecture_01_merge</span>,</span>
<span>                                <span class="va">MCQ_merge</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Joining with `by = join_by(email_address)`</code></pre>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Rename email</span></span>
<span><span class="va">lecture_01_email</span> <span class="op">&lt;-</span> <span class="va">lecture_01_merge</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>email <span class="op">=</span> <span class="va">email_address</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lecture_01_MCQ_left</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">lecture_01_email</span>,</span>
<span>                                <span class="va">MCQ_merge</span>, </span>
<span>                                by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"email"</span> <span class="op">=</span> <span class="st">"email_address"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="right_join" class="section level4" number="7.3.1.2">
<h4>
<span class="header-section-number">7.3.1.2</span> <code>right_join()</code><a class="anchor" aria-label="anchor" href="#right_join"><i class="fas fa-link"></i></a>
</h4>
<p>In contrast, <code><span><span class="fu">right_join</span><span class="op">(</span><span class="op">)</span></span></code> retains all observations in data frame 2, which is the MCQ data in this example.</p>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lecture_01_MCQ_right</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join</a></span><span class="op">(</span><span class="va">lecture_01_merge</span>,</span>
<span>                                  <span class="va">MCQ_merge</span>, </span>
<span>                                  by <span class="op">=</span> <span class="st">"email_address"</span><span class="op">)</span></span></code></pre></div>
<p>It is important you explore the resulting data frame to make sure everything is as expected.</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">lecture_01_MCQ_right</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 243
## Columns: 11
## $ user_name                          &lt;chr&gt; "Yaw, Collin", "Viaan, Jordan", "Su…
## $ email_address                      &lt;chr&gt; "214488@university.ac.uk", "211717@…
## $ total_views                        &lt;dbl&gt; 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 3,…
## $ total_view_time                    &lt;time&gt; 00:00:30, 00:01:00, 00:01:00, 00:0…
## $ average_view_time                  &lt;time&gt; 00:00:30, 00:01:00, 00:01:00, 00:0…
## $ last_viewed                        &lt;chr&gt; "11/04/2022", "09/30/2022", "10/08/…
## $ first_name                         &lt;chr&gt; "Collin", "Jordan", "Hali", "Franki…
## $ surname                            &lt;chr&gt; "Yaw", "Viaan", "Sunny", "Tzivia", …
## $ id_number                          &lt;int&gt; 214488, 211717, 278359, 272061, 275…
## $ quiz_mcq_summative_assessment_real &lt;int&gt; 17, 22, 19, 19, 22, NA, 20, 21, 18,…
## $ quiz_mcq_summative_assessment_perc &lt;dbl&gt; 77.27273, 100.00000, 86.36364, 86.3…</code></pre>
<p>We started with 67 rows for the Echo360 data and 243 rows for the MCQ data, but because we wanted to retain all MCQ observations, we ended up with 243 rows.</p>
</div>
<div id="full_join" class="section level4" number="7.3.1.3">
<h4>
<span class="header-section-number">7.3.1.3</span> <code>full_join()</code><a class="anchor" aria-label="anchor" href="#full_join"><i class="fas fa-link"></i></a>
</h4>
<p>Finally, <code><span><span class="fu">right_join</span><span class="op">(</span><span class="op">)</span></span></code> retains all observations in data frame 1 and data frame 2.</p>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lecture_01_MCQ_full</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join</a></span><span class="op">(</span><span class="va">lecture_01_merge</span>,</span>
<span>                                <span class="va">MCQ_merge</span>, </span>
<span>                                by <span class="op">=</span> <span class="st">"email_address"</span><span class="op">)</span></span></code></pre></div>
<p>It is important you explore the resulting data frame to make sure everything is as expected.</p>
<div class="sourceCode" id="cb131"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">lecture_01_MCQ_full</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 245
## Columns: 11
## $ user_name                          &lt;chr&gt; "Yaw, Collin", "Viaan, Jordan", NA,…
## $ email_address                      &lt;chr&gt; "214488@university.ac.uk", "211717@…
## $ total_views                        &lt;dbl&gt; 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 1, 2,…
## $ total_view_time                    &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:0…
## $ average_view_time                  &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:0…
## $ last_viewed                        &lt;chr&gt; "11/04/2022", "09/30/2022", "02/10/…
## $ first_name                         &lt;chr&gt; "Collin", "Jordan", NA, NA, "Hali",…
## $ surname                            &lt;chr&gt; "Yaw", "Viaan", NA, NA, "Sunny", "T…
## $ id_number                          &lt;int&gt; 214488, 211717, NA, NA, 278359, 272…
## $ quiz_mcq_summative_assessment_real &lt;int&gt; 17, 22, NA, NA, 19, 19, 22, NA, 20,…
## $ quiz_mcq_summative_assessment_perc &lt;dbl&gt; 77.27273, 100.00000, NA, NA, 86.363…</code></pre>
<p>We started with 67 rows for the Echo360 data and 243 rows for the MCQ data, but because we wanted to retain all MCQ observations, we ended up with 245 rows.</p>
<p>To summarise:</p>
<ul>
<li><p>The <code>left</code> join retains all <code>nrow(lecture_01_MCQ_left)</code> student email addresses listed in the Echo360 <code>lecture_01_merge</code> object;</p></li>
<li><p>Tthe <code>right</code> join retains all <code>nrow(lecture_01_MCQ_right)</code> student email addresses listed in the <code>MCQ_merge</code> object;</p></li>
<li><p>The <code>full</code> join retains all <code>nrow(lecture_01_MCQ_full)</code> unique student email addresses listed in both <code>lecture_01_merge</code> and <code>MCQ_merge</code>.</p></li>
</ul>
<p>On inspection, there are two observations in <code>lecture_01_merge</code> that have missing values (<code>NA</code>) for <code>email_address</code> and these correspond to the two "extra" observations in <code>lecture_01_MCQ_full</code> compared to <code>lecture_01_MCQ_right</code>.</p>
</div>
</div>
</div>
<div id="merging-data-where-each-student-may-appear-more-than-once" class="section level2" number="7.4">
<h2>
<span class="header-section-number">7.4</span> Merging data where each student may appear more than once<a class="anchor" aria-label="anchor" href="#merging-data-where-each-student-may-appear-more-than-once"><i class="fas fa-link"></i></a>
</h2>
<p>If we are interested in combining Echo360 data from <em>multiple</em> lectures (and thus where students may appear more than once) together with another data object where the students appear only once (such as the checklist and MCQ data described above), then we can still use the <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> function. Despite the function including the argument <code>multiple</code> for the "handling of rows in x with multiple matches in y", this argument is not relevant to our scenario since if the Echo360 data is the <code>x</code> argument and has multiple rows for each student it can be merged with another data source as the <code>y</code> argument (within which each student only appears once) in one of the ways shown previously.</p>
<p>First, select the variables of interest from each data object, where <code>Echo360_data</code> contains the data from the first three lectures.</p>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Echo360_data_merge</span> <span class="op">&lt;-</span> <span class="va">Echo360_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">user_name</span>, </span>
<span>         <span class="va">email_address</span>,</span>
<span>         <span class="va">media_name</span>,</span>
<span>         <span class="va">total_views</span>,</span>
<span>         <span class="va">total_view_time</span>,</span>
<span>         <span class="va">average_view_time</span>,</span>
<span>         <span class="va">last_viewed</span><span class="op">)</span></span>
<span></span>
<span><span class="va">MCQ_merge</span> <span class="op">&lt;-</span> <span class="va">MCQ</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">first_name</span>,</span>
<span>         <span class="va">surname</span>,</span>
<span>         <span class="va">id_number</span>,</span>
<span>         <span class="va">email_address</span>,</span>
<span>         <span class="va">quiz_mcq_summative_assessment_real</span>,</span>
<span>         <span class="va">quiz_mcq_summative_assessment_perc</span><span class="op">)</span></span></code></pre></div>
<div class="info">
<p>Where students may appear more than once, its necessary to include a variable that distinguishes between the repeated appearances. In this case its the variable <code>media_name</code> which identifies the lecture that the Echo360 data is from.</p>
</div>
<p>Second, specify the type of 'join', in this case there is only one.</p>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Echo360_data_MCQ_left</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">Echo360_data_merge</span>,</span>
<span>                                    <span class="va">MCQ_merge</span>,</span>
<span>                                    by <span class="op">=</span> <span class="st">"email_address"</span><span class="op">)</span></span></code></pre></div>
<p>Third, check that the input and output data objects are as we expect.</p>
<div class="sourceCode" id="cb135"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Dimensions of original echo 360 data</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">Echo360_data_merge</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Dimensions of echo 360 data joined with MCQ data </span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">Echo360_data_MCQ_left</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Rows: 145
## Columns: 7
## $ user_name         &lt;chr&gt; "Yaw, Collin", "Viaan, Jordan", NA, NA, "Sunny, Hali…
## $ email_address     &lt;chr&gt; "214488@university.ac.uk", "211717@university.ac.uk"…
## $ media_name        &lt;chr&gt; "RM1 Lecture 1", "RM1 Lecture 1", "RM1 Lecture 1", "…
## $ total_views       &lt;dbl&gt; 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 1, 2, 1, 3, 3, 1, 1, 5…
## $ total_view_time   &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:04:30, 00:01:00, 0…
## $ average_view_time &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:01:30, 00:01:00, 0…
## $ last_viewed       &lt;chr&gt; "11/04/2022", "09/30/2022", "02/10/2023", "10/21/202…
## Rows: 145
## Columns: 12
## $ user_name                          &lt;chr&gt; "Yaw, Collin", "Viaan, Jordan", NA,…
## $ email_address                      &lt;chr&gt; "214488@university.ac.uk", "211717@…
## $ media_name                         &lt;chr&gt; "RM1 Lecture 1", "RM1 Lecture 1", "…
## $ total_views                        &lt;dbl&gt; 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 1, 2,…
## $ total_view_time                    &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:0…
## $ average_view_time                  &lt;time&gt; 00:00:30, 00:01:00, 00:00:08, 00:0…
## $ last_viewed                        &lt;chr&gt; "11/04/2022", "09/30/2022", "02/10/…
## $ first_name                         &lt;chr&gt; "Collin", "Jordan", NA, NA, "Hali",…
## $ surname                            &lt;chr&gt; "Yaw", "Viaan", NA, NA, "Sunny", "T…
## $ id_number                          &lt;int&gt; 214488, 211717, NA, NA, 278359, 272…
## $ quiz_mcq_summative_assessment_real &lt;int&gt; 17, 22, NA, NA, 19, 19, 22, NA, 20,…
## $ quiz_mcq_summative_assessment_perc &lt;dbl&gt; 77.27273, 100.00000, NA, NA, 86.363…</code></pre>
<p>The <code>left</code> join retains all 145 observations listed in the <code>Echo360_data_merge</code> object and combines them with the (single) corresponding observations in <code>MCQ_merge</code>.</p>
</div>
<div id="visualizing-merged-data" class="section level2" number="7.5">
<h2>
<span class="header-section-number">7.5</span> Visualizing merged data<a class="anchor" aria-label="anchor" href="#visualizing-merged-data"><i class="fas fa-link"></i></a>
</h2>
<p>Merging data enables the exploration of how video engagement (recorded in the Echo360 data) may be related to student performance. For example, the number of times each student views video content can be combined with their performance in an assessment (such as contained in the the MCQ data above).</p>
<p>First, we need some brief wrangling to summarise the total number of video views per student and repeat the joining process from before.</p>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">student_data</span> <span class="op">&lt;-</span> <span class="va">Echo360_data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">email_address</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>total_views <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">total_views</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>email_address <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">email_address</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">student_MCQ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">student_data</span>,</span>
<span>                         <span class="va">MCQ_merge</span>,</span>
<span>                         by <span class="op">=</span> <span class="st">"email_address"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>MCQ_perc <span class="op">=</span> <span class="va">quiz_mcq_summative_assessment_perc</span><span class="op">)</span> <span class="co"># Rename super long name</span></span></code></pre></div>
<p>We now have Echo360 and student attainment data that we can use to explore for potential patterns. For example, we can look at the relationship between these two variables in a scatterplot. There is a lot of overlap, so we have added a little jitter to the data points so its easier to see the density. This is why some of the points look like they extend beyond 100%.</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fig.no_viewed.mcq</span> <span class="op">&lt;-</span> <span class="va">student_MCQ</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">total_views</span>, y <span class="op">=</span> <span class="va">MCQ_perc</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title<span class="op">=</span> <span class="st">"Number of Video Views vs. Percentage Score in an MCQ"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Percentage Score in MCQ (%)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"No. of Video Views"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fig.no_viewed.mcq</span></span></code></pre></div>
<div class="inline-figure"><img src="08-Echo_combine_files/figure-html/merge_plot-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>From this plot, it does not look like there is a clear relationship as there are far more video views between 0 and 5, and clustered in the top left to show very good performance above 80%.</p>
<p>As in the previous chapter, you might want to identify some of these data points in an interactive version of the plot, so you could convert it using <code class="package">plotly</code>:</p>
<div class="sourceCode" id="cb139"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/plotly/man/ggplotly.html">ggplotly</a></span><span class="op">(</span><span class="va">fig.no_viewed.mcq</span><span class="op">)</span></span></code></pre></div>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-9d3d3558c42ada1d33eb" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-9d3d3558c42ada1d33eb">{"x":{"data":[{"x":[1.8949221402406693,1.132533923536539,4.6820285638794301,2.3778170958161353,2.0997370079159738,0.93833447378128765,1.768845946341753,3.0006489373743532,0.73014517202973361,5.1457912681624292,1.9548783939331771,1.1566665200516582,2.0470230804756282,1.3146476166322829,1.1441035950556397,6.6272682324051857,2.1598340507596729,1.2167537696659565,3.163694036193192,6.3590112462639805,1.3869137406349181,0.91959676966071124,2.1998566495254637,2.7212115997448563,3.3520663399249315,0.97799998074769978,1.1048413213342427,10.622723840177059,1.7401143938302994,3.3037448277696968,0.65020241495221853,5.9779194762930272,1.0015888513997198,1.3419560406357052,0.91598160918802018,1.0222423251718282,0.64260369986295696,2.8230396579951047,6.6632386654615399,3.8673164715990422,4.0087468219920996,3.6635758444666862,5.0293472178280352,1.0616789499297739,2.8646805467084051,0.8471119483932853,1.96221832241863,2.1999133301898839,5.8240940930321816,0.98315284438431261,2.3076704807579516,2.9539038449525834,1.0284258918836713,0.91954167820513244,5.0609936865046619,5.0448824819177389,8.6682608619332306,1.0243784422054887,3.2854642903432252,1.2164926711469888,0.6164626581594348,0.74128849357366566,1.3400650035589934,2.2390532976016404,9.6171686762943871,0.70233902391046277,5.852865802310407,2.0078915724530817,0.89833817575126884,0.65973323713988063,2.7149521104991434,15.788173276744782,1.1515916271135211,2.1439516790211202,0.92163308076560502,0.87964044772088523,6.6216236673295494,0.73197106271982193,3.3478084843605758,1.1713184405118227,2.8349945303052664,2.1414160082116722,16.279381401836872,1.0503808224573732,4.2584107184782622,1.1421785226091743,0.71617982089519505,4.761988114006817,1.3569483427330851,0.82305107004940514,1.1437571108341218,6.3324813626706602],"y":[94.63922117752108,86.365490003742948,76.457295074042946,87.435367970981375,85.752891860902309,99.692173579030424,75.794354169206187,101.56261493536559,77.878809220750213,90.062013510614634,90.013274259187952,86.256617933342397,96.726752527227447,92.109707061370656,92.216624162921846,77.096213077787638,82.08069402639839,82.225386792455211,87.529041746800587,90.574771404605016,86.104619801891118,101.27478038807484,100.86955601095475,75.842708144336939,81.854394184086814,71.145547377792283,77.632721548222676,83.635928464884117,72.713174600662157,89.568470272828236,98.539970374073505,null,90.113749974830583,99.768110915849149,94.579660890793264,89.894381065598949,58.526041763411328,84.640745324167341,98.730725685811862,69.310816989534274,93.714976988055497,89.872834320942104,100.89053765447302,82.754128455099746,91.358423617414445,94.73217311738567,80.782109156081631,86.021245629103348,90.553852080960169,76.778990937904879,80.348036657510846,85.682246166874066,100.87358405220915,91.73339300788939,83.493690661747351,97.203502086075858,84.698438210920855,86.645749389109284,78.003148998726488,99.872292242944241,81.129424496638521,100.54333829320967,98.678205368871048,92.362404719672412,86.202965734357178,87.34916940839453,67.349984940480098,98.997203426604926,91.726231776516542,100.25823578661816,93.678475790233776,100.82487952387469,89.561443050307304,86.134809849106446,98.383953887969255,91.186267052015111,88.040137798948706,85.806952241638839,80.139356571334346,58.163624995980754,86.267416331578374,null,84.571314879100427,100.42538962326944,87.01186818324706,90.53405301306735,96.697858056392178,90.846725314516917,95.928025100888178,80.517254632643684,86.242430064488531,null],"text":["total_views:  2<br />MCQ_perc:  95.45455","total_views:  1<br />MCQ_perc:  86.36364","total_views:  5<br />MCQ_perc:  77.27273","total_views:  2<br />MCQ_perc:  86.36364","total_views:  2<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc: 100.00000","total_views:  2<br />MCQ_perc:  77.27273","total_views:  3<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  77.27273","total_views:  5<br />MCQ_perc:  90.90909","total_views:  2<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  86.36364","total_views:  2<br />MCQ_perc:  95.45455","total_views:  1<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  90.90909","total_views:  7<br />MCQ_perc:  77.27273","total_views:  2<br />MCQ_perc:  81.81818","total_views:  1<br />MCQ_perc:  81.81818","total_views:  3<br />MCQ_perc:  86.36364","total_views:  6<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc: 100.00000","total_views:  2<br />MCQ_perc: 100.00000","total_views:  3<br />MCQ_perc:  77.27273","total_views:  3<br />MCQ_perc:  81.81818","total_views:  1<br />MCQ_perc:  72.72727","total_views:  1<br />MCQ_perc:  77.27273","total_views: 11<br />MCQ_perc:  81.81818","total_views:  2<br />MCQ_perc:  72.72727","total_views:  3<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc: 100.00000","total_views:  6<br />MCQ_perc:        NA","total_views:  1<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  95.45455","total_views:  1<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  59.09091","total_views:  3<br />MCQ_perc:  86.36364","total_views:  7<br />MCQ_perc: 100.00000","total_views:  4<br />MCQ_perc:  68.18182","total_views:  4<br />MCQ_perc:  95.45455","total_views:  4<br />MCQ_perc:  90.90909","total_views:  5<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  81.81818","total_views:  3<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  95.45455","total_views:  2<br />MCQ_perc:  81.81818","total_views:  2<br />MCQ_perc:  86.36364","total_views:  6<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  77.27273","total_views:  2<br />MCQ_perc:  81.81818","total_views:  3<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  90.90909","total_views:  5<br />MCQ_perc:  81.81818","total_views:  5<br />MCQ_perc:  95.45455","total_views:  9<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc:  86.36364","total_views:  3<br />MCQ_perc:  77.27273","total_views:  1<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  81.81818","total_views:  1<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc: 100.00000","total_views:  2<br />MCQ_perc:  90.90909","total_views: 10<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc:  86.36364","total_views:  6<br />MCQ_perc:  68.18182","total_views:  2<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc: 100.00000","total_views:  3<br />MCQ_perc:  95.45455","total_views: 16<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  90.90909","total_views:  2<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc: 100.00000","total_views:  1<br />MCQ_perc:  90.90909","total_views:  7<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc:  86.36364","total_views:  3<br />MCQ_perc:  81.81818","total_views:  1<br />MCQ_perc:  59.09091","total_views:  3<br />MCQ_perc:  86.36364","total_views:  2<br />MCQ_perc:        NA","total_views: 16<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc: 100.00000","total_views:  4<br />MCQ_perc:  86.36364","total_views:  1<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  95.45455","total_views:  5<br />MCQ_perc:  90.90909","total_views:  1<br />MCQ_perc:  95.45455","total_views:  1<br />MCQ_perc:  81.81818","total_views:  1<br />MCQ_perc:  86.36364","total_views:  6<br />MCQ_perc:        NA"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,0,0,1)","opacity":1,"size":5.6692913385826778,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)"}},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Number of Video Views vs. Percentage Score in an MCQ","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.16668327902443714,17.062527339020743],"tickmode":"array","ticktext":["0","5","10","15"],"tickvals":[0,5,10,15],"categoryorder":"array","categoryarray":["0","5","10","15"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"No. of Video Views","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[55.993675499011516,103.73256443233483],"tickmode":"array","ticktext":["60","70","80","90","100"],"tickvals":[60,70,80,90,100],"categoryorder":"array","categoryarray":["60","70","80","90","100"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Percentage Score in MCQ (%)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"3eec366c14c8":{"x":{},"y":{},"type":"scatter"}},"cur_data":"3eec366c14c8","visdat":{"3eec366c14c8":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script><p>The purpose of our tutorials has not been to introduce you to inferential statistics, but having the data available means you can explore in different ways. The scatterplot did not suggest there was a clear relationship visually between total video views and MCQ attainment, but maybe there is a subtle statistical relationship.</p>
<p>Here, we can apply a Spearman correlation since the data may not meet parametric assumptions given the distribution of each variable.</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">student_MCQ</span><span class="op">$</span><span class="va">total_views</span>, </span>
<span>         <span class="va">student_MCQ</span><span class="op">$</span><span class="va">MCQ_perc</span>, </span>
<span>         method <span class="op">=</span> <span class="st">"spearman"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning in cor.test.default(student_MCQ$total_views, student_MCQ$MCQ_perc, :
## Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman's rank correlation rho
## 
## data:  student_MCQ$total_views and student_MCQ$MCQ_perc
## S = 133575, p-value = 0.2004
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## -0.1370056</code></pre>
<p>The correlation coefficient is slightly negative suggesting as the number of video views increases, the MCQ percentage tends to decrease, but the relationship is not statistically significant.</p>
<p>This might inspire you to explore additional relationships and variables to see if there patterns worth investigating further to answer research questions you might have.</p>

</div>
</div>



<div class="chapter-nav">
<div class="prev"><a href="Echo_course.html"><span class="header-section-number">6</span> Exploring Echo360 video/course level data with tidyverse</a></div>
<div class="next"><a href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#Echo_combine"><span class="header-section-number">7</span> Combining Echo360 data with other sources of data with tidyverse</a></li>
<li><a class="nav-link" href="#introduction-2"><span class="header-section-number">7.1</span> Introduction</a></li>
<li><a class="nav-link" href="#reading-in-the-data"><span class="header-section-number">7.2</span> Reading in the data</a></li>
<li>
<a class="nav-link" href="#joining-data-using-dplyr"><span class="header-section-number">7.3</span> Joining data using dplyr</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#merging-data-where-each-student-only-appears-once-in-each-data-object"><span class="header-section-number">7.3.1</span> Merging data where each student only appears once in each data object</a></li></ul>
</li>
<li><a class="nav-link" href="#merging-data-where-each-student-may-appear-more-than-once"><span class="header-section-number">7.4</span> Merging data where each student may appear more than once</a></li>
<li><a class="nav-link" href="#visualizing-merged-data"><span class="header-section-number">7.5</span> Visualizing merged data</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/scholaRship/blob/master/book/08-Echo_combine.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/scholaRship/edit/master/book/08-Echo_combine.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;

    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    $(solveme[i]).after(" <span class='webex-icon'></span>");
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    $(selects[i]).after(" <span class='webex-icon'></span>");
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );

  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });

  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script>

</div>
 <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>scholaRship</strong>" was written by Emily Nordmann, Craig Alexander, James Bartlett, Eilidh Jack, Gaby Mahrholz, Jill MacKay, Mitchum Bock. It was last built on 2023-09-05.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
